name: Docker ARM Build
on: [push, workflow_dispatch]

jobs:
  build-reVC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build in ARM Docker
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: bookworm
          githubToken: ${{ github.token }}
          
          # Встановлюємо все всередині ARM-контейнера
          install: |
            apt-get update
            apt-get install -y build-essential cmake git libsdl2-dev libopenal-dev libsndfile1-dev libmpg123-dev libglew-dev

          # Сама компіляція
          run: |
            mkdir build && cd build
            cmake .. -DREVC_PROJECT_NAME=reVC -DREVC_AUDIO=ON -DLIBRW_PLATFORM=GL3 -DLIBRW_GL3_GFXLIB=SDL2
            make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reVC-arm-docker
          path: build/reVC
